x-anchors:
  args: &current-user-info
    user: ${USER:-ubuntu}
    user_id: ${USER_ID:-1000}
    group_id: ${GROUP_ID:-1001}

services:
  app:
    image: picoclaw
    build:
      context: .
      dockerfile: Dockerfile
      args: *current-user-info
    volumes:
      - ./shared:/shared
      - ./picoclaw_data:/home/${USER}/.picoclaw
    environment:
      PICOCLAW_GATEWAY_HOST: 0.0.0.0
#    entrypoint: ""
    ports:
      - 18800:18800

  browser:
    image: browser
    build:
      context: ./browser
      dockerfile: Dockerfile
      args: *current-user-info
    shm_size: 2gb
    ports:
      - "9223:9223"
    volumes:
      - ./browser/chrome-profile:/home/${USER}/chrome-profile
    devices:
      - /dev/dri:/dev/dri
    security_opt:
      - seccomp:unconfined
       